"""Generates <system> entries for ES-DE and writes them directly into
ES-DE's own sanctioned override location: custom_systems/es_systems.xml
(confirmed from ES-DE's own USERGUIDE.md/FAQ.md -- the bundled
resources/systems/<os>/es_systems.xml must NEVER be edited directly, since
it gets overwritten on every ES-DE update; custom_systems is specifically
designed for exactly this kind of customization and survives updates).

Each generated <system> matches the pattern confirmed working end-to-end
(see TESTING.md's Test Log for the bugs this sidesteps by construction):

  - <path> points at roms_stub_root/<system>, never the NAS.
  - <command> calls launch.bat (Windows) / launch.sh (Linux/Mac), which
    fixes the working-directory problem (ES-DE launches commands with its
    own cwd, not this repo's).
  - %ROM% is passed WITHOUT extra quotes -- ES-DE already quotes it when
    needed; adding another layer produces a doubled `""...""` that breaks
    Windows' argument parsing.

Writing to custom_systems is done as a SAFE MERGE, not a blind overwrite:
any existing <system> entries in that file are preserved untouched unless
their <name> matches one of the systems configured in config.yaml, in
which case they're replaced with the freshly generated version. This
means running this repeatedly is safe, and any OTHER custom systems you've
added by hand (outside this project) are never touched.
"""
from __future__ import annotations

import os
import xml.etree.ElementTree as ET
from pathlib import Path

from .config import Config
from .system_names import COMMON_FULLNAMES

_REPO_ROOT = Path(__file__).resolve().parent.parent


def _launch_script() -> Path:
    return _REPO_ROOT / ("launch.bat" if os.name == "nt" else "launch.sh")


def _build_system_element(config: Config, system_name: str) -> ET.Element:
    sys_cfg = config.systems[system_name]
    # Always resolve to an absolute path, regardless of how config.yaml
    # expressed roms_stub_root (relative paths there are fine for our own
    # CLI commands, since we're always run from the repo root -- but ES-DE
    # resolves <path> against ITS OWN working directory, not ours, so a
    # relative path here would silently point somewhere wrong).
    stub_path = (config.roms_stub_root / system_name).resolve()
    extensions = " ".join(sys_cfg.extensions)
    fullname = sys_cfg.fullname or COMMON_FULLNAMES.get(system_name.lower(), system_name)
    theme = sys_cfg.theme or system_name
    launch_script = _launch_script()

    system_el = ET.Element("system")
    ET.SubElement(system_el, "name").text = system_name
    ET.SubElement(system_el, "fullname").text = fullname
    ET.SubElement(system_el, "path").text = str(stub_path)
    ET.SubElement(system_el, "extension").text = extensions
    ET.SubElement(system_el, "command").text = f'"{launch_script}" {system_name} %ROM%'
    ET.SubElement(system_el, "platform").text = system_name
    ET.SubElement(system_el, "theme").text = theme
    return system_el


def generate_system_entry(config: Config, system_name: str) -> str:
    """Returns one <system> block as a formatted string -- used for
    review-only output (--output flag), not the direct-write path."""
    el = _build_system_element(config, system_name)
    ET.indent(el, space="  ")
    return ET.tostring(el, encoding="unicode")


def generate_all(config: Config) -> str:
    """All configured systems as a standalone XML fragment, for
    review-only output. Not what gets written to custom_systems -- see
    write_custom_systems for the direct-write, safe-merge path."""
    header = (
        "<!-- Generated by `python -m src.cli generate-es-systems --output <path>`.\n"
        "     This is a REVIEW-ONLY dump -- normally `generate-es-systems` writes\n"
        "     directly to custom_systems/es_systems.xml instead (safe merge, see\n"
        "     that command's docstring). Required es_settings.xml changes (see\n"
        "     TESTING.md): ParseGamelistOnly=true, LegacyGamelistFileLocation=false\n"
        "     (or unset), MediaDirectory unset (default). -->\n"
    )
    entries = [generate_system_entry(config, name) for name in config.systems]
    return header + "\n\n".join(entries) + "\n"


def write_custom_systems(config: Config) -> Path:
    """Safely merges all configured systems into ES-DE's own
    custom_systems/es_systems.xml: replaces any existing <system> entries
    whose <name> matches a system we manage, leaves everything else in
    that file untouched, and creates the file/directory if neither exists
    yet. Returns the path written.
    """
    target = config.custom_systems_path()
    target.parent.mkdir(parents=True, exist_ok=True)

    if target.exists():
        tree = ET.parse(target)
        root = tree.getroot()
    else:
        root = ET.Element("systemList")

    our_names = set(config.systems.keys())

    # Remove any existing entries for systems we're about to regenerate,
    # so re-running this doesn't create duplicates. Anything NOT in
    # our_names (systems added by hand, or by some other tool) is left
    # exactly as-is.
    for existing in list(root.findall("system")):
        name_el = existing.find("name")
        if name_el is not None and name_el.text in our_names:
            root.remove(existing)

    for system_name in config.systems:
        root.append(_build_system_element(config, system_name))

    ET.indent(root, space="  ")
    tree = ET.ElementTree(root)
    tree.write(target, encoding="utf-8", xml_declaration=True)
    return target
