"""System key -> proper display name, used as the default <fullname> in
generated es_systems.xml entries when a system's config.yaml entry doesn't
set its own `fullname` explicitly. Uses the same key vocabulary as
scrapers/screenscraper_ids.py for consistency.

Not exhaustive -- unknown keys fall back to the raw system name (see
es_systems_generator.py). Add an explicit `fullname:` in config.yaml for
anything missing here or where a different name is preferred.
"""

COMMON_FULLNAMES: dict[str, str] = {
    "3do": "3DO",
    "3ds": "Nintendo 3DS",
    "amiga": "Amiga",
    "amstradcpc": "Amstrad CPC",
    "apple2": "Apple II",
    "arcade": "Arcade",
    "atari800": "Atari 800",
    "atari2600": "Atari 2600",
    "atari5200": "Atari 5200",
    "atari7800": "Atari 7800",
    "atarijaguar": "Atari Jaguar",
    "atarijaguarcd": "Atari Jaguar CD",
    "atarilynx": "Atari Lynx",
    "atarist": "Atari ST",
    "c64": "Commodore 64",
    "coleco": "ColecoVision",
    "dreamcast": "Dreamcast",
    "fds": "Famicom Disk System",
    "gamegear": "Game Gear",
    "gb": "Game Boy",
    "gba": "Game Boy Advance",
    "gbc": "Game Boy Color",
    "gc": "GameCube",
    "genesis": "Genesis",
    "megadrive": "Mega Drive",
    "intellivision": "Intellivision",
    "mastersystem": "Master System",
    "megacd": "Mega CD",
    "segacd": "Sega CD",
    "msx": "MSX",
    "msx2": "MSX2",
    "n64": "Nintendo 64",
    "nds": "Nintendo DS",
    "neogeo": "Neo Geo",
    "neogeocd": "Neo Geo CD",
    "nes": "Nintendo Entertainment System",
    "ngp": "Neo Geo Pocket",
    "ngpc": "Neo Geo Pocket Color",
    "pc": "PC",
    "pc98": "PC-98",
    "pcengine": "PC Engine",
    "pcenginecd": "PC Engine CD",
    "pcfx": "PC-FX",
    "ps2": "PlayStation 2",
    "psp": "PlayStation Portable",
    "psx": "PlayStation",
    "saturn": "Saturn",
    "scummvm": "ScummVM",
    "sega32x": "Sega 32X",
    "sg-1000": "SG-1000",
    "snes": "Super Nintendo",
    "switch": "Switch",
    "vectrex": "Vectrex",
    "vic20": "VIC-20",
    "virtualboy": "Virtual Boy",
    "wii": "Wii",
    "wiiu": "Wii U",
    "wonderswan": "WonderSwan",
    "wonderswancolor": "WonderSwan Color",
    "x68000": "Sharp X68000",
    "zxspectrum": "ZX Spectrum",
}
